Add support for ROS 2 (Humble)
choreonoid/choreonoid_ros pull request #18
Opened 2024-03-02 02:22 UTC by HansRobo

## abstruct

I imported derverbles from choreonoid/choreonoid_ros2 and added some fixes.
With this pull-request, this repository is configured to be buildable on both ROS 1 and ROS 2.

The major differences between ROS 1 version and ROS 2 version are as follows.

## ROS configuration

### ROS 1

- A choreonoid app containing a ROS plugin behaves as a single context, a node.
- The plugin initialization blocks the choreonoid app launch if there is no connection to roscore.

### ROS 2

- Since there is no ROS 2-related processing in plugin initialization, it does not block the app launch.
- ROS 2 plugin can be loaded and used in choreonoid app without modification for the plugin.
- Each of WorldROS2Item and BodyROS2Item operates as its own context and node for each instance of the item.

## ros_control support

### ROS 1

ros_control support is available now.

### ROS 2

ros_control support is not available now.
However, we plan to support it in the future.

## Build instruction for ROS 2 (Humble, Ubuntu22.04)

```bash
mkdir -p cnoid_ws/src
cd cnoid_ws/src
git clone git@github.com:choreonoid/choreonoid.git
git clone -b merge_choreonoid_ros2 git@github.com:choreonoid/choreonoid_ros.git
cd ..
source /opt/ros/humble/setup.bash
rosdep install -iy --from-paths src
colcon build --symlink-install
```

Note: Please ignore the error from choreonoid with catkin, when running rosdep

2024-03-02 09:18 UTC, ssr-yuki requested changes
Thank you for your fantastic development. I leave some comments for improvement and clarification of the codes.

While we still need to work for further implementation, we now get a foot in the door of ROS 2 with your PR!

2024-03-02 09:18 UTC, ssr-yuki commented on src/node/choreonoid_ros2.cpp
> +    auto plugin_path = ament_index_cpp::get_package_share_directory("choreonoid_ros2") + "/../../lib/choreonoid_ros2";
In my environment, this line does not work: executing Choreonoid with `ros2 run` fails. Should we replace "choreonoid_ros2" into "choreonoid_ros"?

2024-03-02 09:18 UTC, ssr-yuki commented on src/node/choreonoid_ros2.cpp
> +namespace filesystem = stdx::filesystem;
Viewing the whole of this file, I guess this lines are unnecessary. Please let me know if you use this anywhere.

I would also like to point out that this file explicitly write `cnoid::` in some lines while it is `using namespace cnoid`. Could you unify the codes into either style? (I personally prefer not to use `using namespace` directives.)

2024-03-02 09:18 UTC, ssr-yuki commented on src/plugin/BodyROS2Item.cpp
> +    archive.write("body_ros_version", 0);
The parameter `body_ros_version` is no longer used as not restored in the next function.

2024-03-02 09:18 UTC, ssr-yuki commented on src/plugin/BodyROS2Item.cpp
> +typedef sensor_msgs::msg::PointCloud2 PointCloudTypeForRangeSensor;
Please delete this typedef, which is no longer used. The empty line L14 is also removable.

2024-03-02 09:18 UTC, ssr-yuki commented on src/plugin/BodyROS2Item.cpp
> +                                                                  1000);
just my interest: is 1000 a good choice in ROS 2 publication?

2024-03-02 09:18 UTC, ssr-yuki commented on src/plugin/WorldROS2Item.h
> +#define CNOID_ROS_PLUGIN_WORLD_ROS_ITEM_H
should be `~_ROS2_ITEM_H`.

2024-03-08 00:53 UTC, HansRobo commented on src/node/choreonoid_ros2.cpp
> +    auto plugin_path = ament_index_cpp::get_package_share_directory("choreonoid_ros2") + "/../../lib/choreonoid_ros2";
Fixed in https://github.com/choreonoid/choreonoid_ros/pull/18/commits/2af846c245b1e791a3d3f73631c15a8d2c57b242

2024-03-08 00:53 UTC, HansRobo commented on src/plugin/WorldROS2Item.h
> +#define CNOID_ROS_PLUGIN_WORLD_ROS_ITEM_H
Fixed in https://github.com/choreonoid/choreonoid_ros/pull/18/commits/54d8bc3b13d89ebebcb4b816785a2a907d14c989

2024-03-08 00:54 UTC, HansRobo commented on src/plugin/BodyROS2Item.cpp
> +typedef sensor_msgs::msg::PointCloud2 PointCloudTypeForRangeSensor;
Fixed in https://github.com/choreonoid/choreonoid_ros/pull/18/commits/54d8bc3b13d89ebebcb4b816785a2a907d14c989

2024-03-08 00:54 UTC, HansRobo commented on src/node/choreonoid_ros2.cpp
> +namespace filesystem = stdx::filesystem;
Fixed in https://github.com/choreonoid/choreonoid_ros/pull/18/commits/1f681d773093b319e364a62a441848a438f70f4f

2024-03-08 01:14 UTC, HansRobo commented on src/plugin/BodyROS2Item.cpp
> +                                                                  1000);
The history depth for publisher should be comprehensively judged based on the cycle of publication, the importance of the content, the environment, etc.
I don't think 1000 (which can withstand 10 seconds of communication loss) is appropriate.
The old joint state has almost no value, so if a communication breakdown occurs, the old data should be dropped and new data published.
This is the same between ROS 1 and 2.

2024-03-12 07:08 UTC, ssr-yuki approved these changes
Thank you very much!

2024-03-12 07:12 UTC, merged