Add ROSControlItem
choreonoid/choreonoid_ros pull request #5
Opened 2021-05-26 12:07 UTC by RyodoTanaka

ControllerItem を利用した ROS Control の実装を行いました．

https://github.com/choreonoid/cnoid_tank_pkgs/pull/1

上記 PR に検証方法を記載していますが，こちらにも記しておきます．
よろしくお願いします．

```bash
$ roslaunch cnoid_tank_bingup choreonoid.launch
```

上記コマンドで，ROSControlItem を利用したシミュレーションが起動できます．
その後，別ターミナルにて

```bash
$ rqt __ns:=Tank
```
で rqt gui を起動した後， Plugins -> Robot Tools -> Joint trajectory controller から動作確認が可能です．

以上，よろしくお願いします．

2021-06-20 11:22 UTC, ssr-yuki requested changes
コードレビューしました．
~動作確認は追って行います．~ 動作確認もできました．

C++をROSのスタイルに合わせるのであれば，ご修正の際にclang-format等フォーマッタ通してもらうといいのかなと思いました．よろしくお願いします．

2021-06-20 11:22 UTC, ssr-yuki commented on CMakeLists.txt
> +  angles
長期手なメンテナンス性の視点から，既存パッケージ含めアルファベット順に整理していただいた方が良いかと思いました．

2021-06-20 11:22 UTC, ssr-yuki commented on package.xml
> +  <depend>angles</depend>
CMakeと同じく既存パッケージ含めアルファベット順に整理していただいた方が良いかと思いました．

2021-06-20 11:22 UTC, ssr-yuki commented on src/plugin/ROSControlItem.h
> +  virtual void stop(void) override;
C++なのでvoid引数は不要かと思います．
他の関数含めまとめて削除をお願いします．

2021-06-20 11:22 UTC, ssr-yuki commented on src/plugin/ROSControlItem.h
> +  boost::shared_ptr<hardware_interface::RobotHWSim<cnoid::ControllerIO*>> rbt_hw_sim_;
`boost::shared_ptr`を使っている理由がplugin_libの問題である旨一言コメント入れておいていただければと思います．

2021-06-20 11:22 UTC, ssr-yuki commented on src/plugin/robot_hw_cnoid.cpp
> +/////////////////////////////////
既存ファイルのことを鑑み，ファイル名のキャメルケース化をご検討いただければと思います．

2021-06-20 11:22 UTC, ssr-yuki commented on src/plugin/robot_hw_cnoid.h
> +#include <control_toolbox/pid.h>
必須ではないですが，欲を言えばinclusion order揃っていると嬉しいです．
https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

2021-06-20 11:22 UTC, ssr-yuki commented on src/plugin/robot_hw_cnoid.h
> +  std::vector<transmission_interface::TransmissionInfo> tmss_;
この変数名はわかりづらい気がします……

2021-06-20 11:22 UTC, ssr-yuki commented on src/plugin/robot_hw_cnoid.h
> +  uint dof_{0};
`uint`はC++の仕様にはないので，`unsigned int`に書き換えてください．

2021-06-20 11:22 UTC, ssr-yuki commented on src/plugin/robot_hw_cnoid.cpp
> +bool RobotHWCnoid::registerJointLimits(const uint& i)
`uint` -> `unsigned int`

2021-06-20 12:39 UTC, ssr-yuki commented
ちなみにbringupがtypoなので正しくは↓ですね．

```bash
roslaunch cnoid_tank_bringup choreonoid.launch
```

2021-06-28 16:05 UTC, s-nakaoka commented
@RyodoTanaka さん、@ssr-yuki さん、ありがとうございます。
本件当方開発環境にて整理してからmasterにマージします。
今回コミットの改良をひとつのコミットにまとめて、 @ssr-yuki さんのレビュー内容も考慮した上で（ @ssr-yuki さんの協力も受けながら）整理したいと思います。
よろしくお願いします。

2021-06-28 16:05 UTC, closed without merging